package org.schoen.ben.euler;

/**
 * Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
 *
 * Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
 * Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
 * Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
 * It can be verified that T285 = P165 = H143 = 40755.
 *
 * Find the next triangle number that is also pentagonal and hexagonal.
 *
 *
 * @author <a href="mailto:ben.schoen@itris.nl">Ben Schoen</a>
 * @since Nov 9, 2014
 */
public class Problem045 extends AbstractEulerProblem {

	public Problem045(String answer) {
		super(answer);
	}

	@Override
	public void run() {
		long answer = 0;
		long a = 285;
		long b = 166;
		long c = 144;

		for(;;) {
			long t = a * (a + 1) / 2;
			long p = b * (3 * b - 1) / 2;
			long h = c * (2 * c - 1);

			long temp = Math.min(Math.min(t, p), h);
			if(t == p && p == h) {
				answer = p;
				break;
			}
			if(temp == t) {
				a++;
			} else if(temp == p) {
				b++;
			} else {
				c++;
			}
		}
		setAnswer(String.valueOf(answer));
	}

	@Override
	public String getProblemName() {
		return "Problem 45: Find the next triangle number that is also pentagonal and hexagonal.";
	}

}
