package org.schoen.ben.euler;

import java.math.*;
import java.util.*;

/**
 * Consider all integer combinations of ab for 2 ≤ a ≤ 5 and 2 ≤ b ≤ 5:
 *
 * 22=4, 23=8, 24=16, 25=32
 * 32=9, 33=27, 34=81, 35=243
 * 42=16, 43=64, 44=256, 45=1024
 * 52=25, 53=125, 54=625, 55=3125
 * If they are then placed in numerical order, with any repeats removed, we get the following sequence of 15 distinct terms:
 *
 * 4, 8, 9, 16, 25, 27, 32, 64, 81, 125, 243, 256, 625, 1024, 3125
 *
 * How many distinct terms are in the sequence generated by ab for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?
 *
 *
 * @author <a href="mailto:ben.schoen@itris.nl">Ben Schoen</a>
 * @since Oct 29, 2014
 */
public class Problem029 extends AbstractEulerProblem {

	public Problem029(String answer) {
		super(answer);
	}

	@Override
	public void run() {
		Set<BigInteger> terms = new HashSet<>();
		for(int a = 2; a <= 100; a++) {
			for(int b = 2; b <= 100; b++) {
				terms.add(new BigInteger(String.valueOf(a)).pow(b));
			}
		}
		setAnswer(String.valueOf(terms.size()));
	}

	@Override
	public String getProblemName() {
		return "Problem 29: How many distinct terms are in the sequence generated by a^b for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?";
	}

}
